config/routes.rb
Rails.application.routes.draw do
  


  resources :remote_files do
    member do
      get :download
      get :showf
    end
  end

  resources :folders
  resources :servers
  resources :files
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'remote_files#index'
end

app/models/remote_file.rb
require 'mini_magick'
require 'image_optim'

class RemoteFile < ApplicationRecord
  belongs_to :folder
  delegate :server, to: :folder

  scope :smallest_first, -> { order('size asc') }
  scope :not_downloaded, -> { where("status <> ? or status is NULL", 'downloaded') }
  scope :failed, -> { where(status: 'failed') }
  scope :downloaded, -> { where(status: 'downloaded') }

  SIZES = {
    :small => "400"
  }

  module Coder
    extend self

    def dump(object)
      YAML.dump(object)
    rescue => e
      if e.to_s.include?("invalid byte sequence")
        fixed = object.to_s.encode("UTF-8", invalid: :replace, undef: :replace)

        YAML.dump(eval(fixed)) # rescue binding.pry
      else
        raise
      end
    end

    def load(string)
      string.nil? ? {} : YAML.load(string)
    end
  end

  # serialize :image_metadata, Coder

  def fetch_original(force = false)
    already_exists = File.exists?(local_path)    
    rm if already_exists && force

    unless already_exists
      server.ftp.getbinaryfile(path, local_path)
    end

    save_metadata_and_keywords
    save_title
    save_author
    save_capt
    save_credit
    save_data
    save_src
  end

  def save_metadata_and_keywords
    update_attributes(:keywords => keywords_from_image) rescue nil
    File.write(local_path + '.md', original.data)
  end


  def save_title
    update_attributes(:title => title_from_image) rescue nil
  end

  def save_author
    update_attributes(:author => author_from_image) rescue nil
  end

  def save_capt
    update_attributes(:caption => capt_from_image) rescue nil
  end

  def save_credit
    update_attributes(:credit => credit_from_image) rescue nil
  end

  def save_data
    update_attributes(:data => data_from_image) rescue nil
  end

  def save_src
    update_attributes(:src => credit_from_image) rescue nil
  end

  def downloaded?
    File.exists?(local_path) && size == File.size(local_path)
  end

  def downloading?
    File.exists?(local_path) && File.size(local_path) < size
  end
  
  def download_if_missing
    if !downloaded?
      fetch_original
      symlink!
    end
  end


  def download_progress
    File.size(local_path).to_f / size
  end

  def local_path(type = :original)
    File.join(folder.local_path(type), name)
  end

  def rm(type = :original)
    `rm -rf "#{local_path(type)}"`
  end

  def full_path(type = :original)
    File.path(folder.local_path, name)
  end

  def type_exists?(type = :original)
    File.exists?(local_path(type))
  end

  def self.smallest
    smallest_first.first
  end

  def original
    MiniMagick::Image.open(local_path)
  end

  def keywords_from_image
    original.data["profiles"]["iptc"]["Keyword[2,25]"].join(", ")
  end

  def title_from_image
    original.data["profiles"]["iptc"]["Headline[2,105]"].join(" ")
  end

  def author_from_image
    original.data["profiles"]["iptc"]["Byline[2,80]"].join(" ")
  end

  def caption_from_image
    original.data["profiles"]["iptc"].values_at("Headline[2,105]", "Created Date[2,55]", "Caption[2,120]", "Byline[2,80]", "Credit[2,110]", "Keyword[2,25]").join(" ")
  end

  def credit_from_image
    original.data["profiles"]["iptc"]["Src[2,115]"].join(" ")
  end

  def data_from_image
    original.data["profiles"]["iptc"]["Created Date[2,55]"].join(" ")
  end

  def credit_from_image
    original.data["profiles"]["iptc"]["Src[2,115]"].join(" ")
  end

  def create_all_types
    SIZES.keys.each { |type| create_type(type) }
  end

  def create_type(type)
    o = original
    size = SIZES[type]
    
    o.resize size 
    o.strip
    o.write local_path(type)

    ImageOptim.optimize_image!(local_path(type))
  end

  include Symlink
end

app/models/remote_file/symlink.rb
module RemoteFile::Symlink
  def symlink_name(type = :small)
    ext = name.split('.').last
    symlink_name = "#{id}_#{type}.#{ext}"
  end
  
  def symlink_dir
    "#{Rails.root}/app/assets/images"
  end

  def symlink_path(type = :small)
    File.join symlink_dir, symlink_name(type)
  end

  def symlink!(type = :small)
    sl_name = symlink_name(type)
    `cd #{symlink_dir} && rm -rf #{sl_name} && ln -s "#{local_path(type)}" #{sl_name}`
  end

  def symlink_exists?(type = :small)
    File.exists? symlink_path(type)
  end
end

app/controllers/remote_files_controller.rb
class RemoteFilesController < ApplicationController
  before_action :find_file, only: [:download, :showf, :show]

  http_basic_authenticate_with name: "qwe", password: "123" 

    def download
      FetchFileJob.perform_later(params[:id])
      @file.update_attributes(status: 'downloading')
      redirect_back(fallback_location: @file.folder)
      send_file @file.local_path
    end

    def index
      scope = RemoteFile.all
      
      if params[:q]
        scope = scope.where("LOWER(keywords) like '%#{params[:q].downcase}%'")
      end

      @files = scope
    end

    def find_file
      @file = RemoteFile.find(params[:id])
    end

    def showf
      @file.download_if_missing
      send_file @file.local_path
    end

    # def send
    #   begin
    #     send_file @file.file_path
    #   rescue
    #     flash[:error] = 'File not found.'
    #   end
    # end

    # def show
    #   @file = RemoteFile.find(params[:id])

    #   respond_to do |format|
    #   format.html
    #   format.jpg { render pdf: generate_pdf(@file) }
    # end




  def jpg
    file_name = params[:feed_image_path].split('/').last
    @filename ="#{Rails.root}/remote_files_path/#{file_name}"
    send_file(@filename ,
    :type => 'application/pdf/docx/html/htm/doc',
    :disposition => 'attachment')           
  end

end

app/helpers/remote_files_helper.rb
module RemoteFilesHelper
end

app/views/remote_files/_file_card.html.slim
table.table
  thead
    tr
      th Name
      th Size
      th Folder
      th Keywords
      th Caption
      th Title
      th Author
      th Credit

  tbody
      - if file.type_exists?(:small)

      tr
        td = file.name
        td = number_to_human_size(file.size).gsub(" ", "&nbsp;").html_safe
        td = link_to(file.folder.path, file.folder)
        td = file.keywords
        td = file.capt
        td = file.title
        td = file.author
        td = file.credit
        td 
          - if file.type_exists?(:small)
            = try_image_tag(file)
          - else

            - if file.status == 'downloading'
              i.fas.fa-spinner
            - else
              = link_to download_remote_file_path(file) do
                i.fas.fa-file-download

app/views/remote_files/_file_table.html.slim
-@files.sort_by(&:name).each do |file|
  .card-footer
  	.border-right
		  = link_to file
		      - if file.type_exists?(:small)
		          = try_image_tag(file)

app/views/remote_files/_modal.html.slim
.btn 
  .btn-primary               
    .modal
      .modal-dialog
        .modal-content
          - if file.type_exists?(:small)
            = try_image_tag(file)

app/views/remote_files/index.html.slim
- content_for :page_header, "Files matching \"#{params[:q]}\""
.content
    .row       
       = render 'file_table'
       

app/views/remote_files/show.html.slim
- content_for :page_header, @file.title
table.table
  thead
   	tr	 		
	 		ul
   			th  = link_to showf_remote_file_path(@file) do
             = try_image_tag @file
         
                
	
 
tbody
  tr
    td
			  p= @file.data				  
			 	p= @file.caption
			  p= @file.author
				p= @file.data
			  p= @file.credit
				p=
				p= @file.capt